version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
    environment:
      - CONFIG_PATH=/app/config.yaml
      - DATABASE_URL=postgresql://postgres:Omsairam@1922@db:5432/stock_fundamentals
      - REDIS_URL=redis://redis:6379/0
    restart: unless-stopped

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Omsairam@1922
      - POSTGRES_DB=stock_fundamentals
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  worker:
    build: .
    depends_on:
      - api
      - db
      - redis
    volumes:
      - ./:/app
    environment:
      - CONFIG_PATH=/app/config.yaml
      - DATABASE_URL=postgresql://postgres:Omsairam@1922@db:5432/stock_fundamentals
      - REDIS_URL=redis://redis:6379/0
    command: ["python", "-m", "src.stockalpha.worker.main"]
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
