# Type stubs for the logging module
from typing import Any, Optional

class Logger:
    def __init__(self, name: str, level: int = ...) -> None: ...
    def debug(self, msg: object, *args: Any, **kwargs: Any) -> None: ...
    def info(self, msg: object, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, msg: object, *args: Any, **kwargs: Any) -> None: ...
    def error(self, msg: object, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, msg: object, *args: Any, **kwargs: Any) -> None: ...
    def exception(self, msg: object, *args: Any, **kwargs: Any) -> None: ...

def getLogger(name: Optional[str] = ...) -> Logger: ...
def basicConfig(**kwargs: Any) -> None: ...
